### ISSUE TITLE
Split extension into smaller parts?

### ISSUE THREAD

**Issue by cholmes** [stac-extensions/raster#1]
As @m-mohr commented on gitter: 'The extension is rather large/complex. Would it make sense to split it into two parts? Especially thinking about the composition things.'

One thing I felt was that the overview_max_gsd didn't seem to fit super cleanly - like mentioning GSD seems like maybe it wouldn't apply to all rasters? And color_interpretation feels like a 'rendering hint' as well, and even the composites I could see more there. Maybe we actually make the rendering hints extension and put some of this stuff there...

**Comment by matthewhanson** [comment]
I think `stats` could be it's own, clearly defined extension:

**Comment by emmanuelmathot** [comment]
as replied in #2:
> I actually am more favorable for a `stats` object. IMO, we need to clarify first the "band" object concept. If `bands` would become a "core" object, then I see more a proper statistics extension with specific fields for `bands`

**Comment by emmanuelmathot** [comment]
As a more general comment, I agree on the fact that the proposed extension is quite heavy but this is because it gathers together many information to achieve the goal of information better about the pixel value in the raster and all the possibilities of processing and viewing the data inside.
At Terradue, we have concrete use cases already in operations with workarounds (sometimes "ugly") of the current spec. For instance, the radiometric calibration use case (offset, gain, solar irradiance) is essential to produce proper TOA reflectances on optical sensor. With the amazing technologies such as COG and the dynamic tiling allowing processing pixels "on the fly", we can keep the raw data from the provider in the assets and propose processing levels "on-demand" from the STAC item without further background processing and thus saving storage space.

**Comment by cholmes** [comment]
> So, I do not have fundamentally a problem in splitting the extension but I want to keep in mind the achievement of practical use cases.

For sure. At the very least we should make a good tutorial explaining what extensions to use to STAC as you are doing, and it could even make sense to have a 'meta extension' like [card4l](https://github.com/stac-extensions/card4l/blob/main/optical/README.md), that references a number of other extensions. 

The main goal in splitting it up is so that people can use just the 'parts', as there are many useful pieces here.

**Comment by emmanuelmathot** [comment]
Discussed in meetup and transferred in #10.
