### ISSUE TITLE
Raster Palette

### ISSUE THREAD

**Issue by kylebarron** [stac-extensions/raster#17]
Was looking at this [new public landcover dataset](https://caitlin-kontgis.medium.com/mapping-the-world-in-unprecedented-detail-7c0513205b90) and pondering how to make a STAC that represents it. Seems like it could make sense to have palette/colormap values encoded in the raster extension?

**Comment by cholmes** [comment]
I think this is most in line with this 'values' [mapping object](https://github.com/stac-extensions/file#mapping-object) that we had in file. It clearly doesn't belong in file, I recently realized it was still there and filed an issue - https://github.com/stac-extensions/file/issues/6 I think we felt it was worth its own extension instead of putting it in raster, and @m-mohr started https://github.com/stac-extensions/classification I could also see it going directly in raster, but I'm forgetting why we didn't want it there. Though that's not quite all the way to the palette / color map. That could make sense in the 'rendering hints' extension, which I think I never quite got over the line, though most of the functionality desired ended up elsewhere. 

Anyways, round about answer to say +1, would be great to have that somewhere. And I'd like to use it for Planet UDM data as well, to render our cloud / cloud shadow / clear / etc masks.

**Comment by m-mohr** [comment]
Yes, it would be great if someone could make a proposal based on `file:values` in the existing or a new repo. I won't have the time, unfortunately.

**Comment by kylebarron** [comment]
cc @lossyrob since he might be making a catalog on that dataset anyways, ref: https://twitter.com/lossyrob/status/1408450219793072130

**Comment by lossyrob** [comment]
The color maps are baked directly into the COG, in case that's useful info.

I'll take a look at this, not sure if I'll get time to fit in extension spec PR -> new version release -> PySTAC extensions changes before the API release...in case someone else wants to contribute that quickly (looking at you @kylebarron 😉 )

**Comment by emmanuelmathot** [comment]
A color palette metadata is totally inline with raster extension. It was initially proposed but postponed for a future version because it was not clear if color interpretation should be part of a kind of `rendering hints` extension.

> Yes, it would be great if someone could make a proposal based on `file:values` in the existing or a new repo. I won't have the time, unfortunately.

Here, I am not sure we are all talking about the same thing. Values is more about data interpretation and would be larger than color definition only.

**Comment by kylebarron** [comment]
> Here, I am not sure we are all talking about the same thing. Values is more about data interpretation and would be larger than color definition only.

Agreed there's a subtle difference here. Considering the original landcover dataset that made me start this issue, there's a colormap stored within the COGs that maps data values to colors, but that isn't really a sufficient interpretation. Ideally you'd want an association from data value to color and _also_ title/description.

**Comment by lossyrob** [comment]
Would it make more sense to have this as part of the [label](https://github.com/stac-extensions/label) extension? E.g. an optional property on the Class object for "color". @kbgg I think you or other RE folk had been looking at something related, cc'ing you in case there's thoughts here.

**Comment by m-mohr** [comment]
In my use case it doesn't make sense, because it's all asset-based and as far as I understand the label extension is mostly item-based (and requires numerous additional fields, which I don't need).

**Comment by m-mohr** [comment]
I'm finally going to need some kind of replacement for `file:values`, which allows me to express the interpretation (description) for values in each file and/or raster band. There are probably more use cases as indicated above so that's also why the idea was to make it a separate extension, but I won't have a lot of time to wait for this. So how can we proceed with this?

**Comment by m-mohr** [comment]
Would it make sense to make this a field that can be used in raster:bands and/or eo:bands and gives a mapping between values and corresponding metadata?

e.g. something like
```
...
"assets": {
  "data": {
    "href": "example.tif",
    "type": "image/tiff; profile=geotiff",
    "roles": ["data"],
    "raster:bands": {
      "classification:values": [
        {
          "values": [0],
          "description": "Valid data",
          "color": "#000000"
        },
        {
          "values": [1],
          "description": "Clouds",
          "color": "#ffffff"
        },
        {
          "values": [2,3],
          "description": "Clouds Shadows",
          "color": "#cccccc"
        }
      ]
    }
  }
}
...
```

This is just a made-up example. Please change/expand/change with whatever your use-case requires.

**Comment by emmanuelmathot** [comment]
For my understanding from your example: There would be a classification extension applicable at different level (asset or raster band), right?

**Comment by m-mohr** [comment]
Yes

**Comment by drwelby** [comment]
I have a couple days next week I could devote to hashing out this topic and https://github.com/stac-extensions/classification.

**Comment by m-mohr** [comment]
@drwelby Great, go ahead. I'm happy to review. Let me know if you need access rights to that repo or so.

**Comment by drwelby** [comment]
@m-mohr No problems cloning, I'll start an issue for gathering any input on improvements.

**Comment by zakjan** [comment]
I would like to bring to the attention that there are datasets with continuous floating-point values that would benefit from a color palette as well. There was a great discussion at https://github.com/radiantearth/stac-spec/pull/879. However, all the currently existing proposals, this, [file:values](https://github.com/stac-extensions/file#mapping-object) or [classification](https://github.com/stac-extensions/classification), they seem to be focused on mapping discrete values.

Providing a support for a color palette with continuous floating-point values would be helpful for weather / meteorological / climatological data, because it allows highlighting important data value ranges to the user. We can use the explicit color palette to display a legend as well.

Default color palette
<img src="https://user-images.githubusercontent.com/173585/163872360-ee6e3361-1020-4c7f-b3c8-9ffa247910ed.png" width="360">
vs.
Explicit color palette
<img src="https://user-images.githubusercontent.com/173585/163871006-6d3b4594-dd91-41c3-af79-1c89042cd551.png" width="360">
<img src="https://user-images.githubusercontent.com/173585/163871113-f4a8e632-af8c-4688-8159-479bcc44f768.png" width="250">

The most lightweight format for a color palette is an array of tuples of values and colors. The values designate breakpoints, and the color is linearly interpolated between the breakpoints. Such breakpoints don't have any textual description. The colors can be in either RGB or HSL color space, to allow HSL color interpolation.

Further improvements for consideration: logarithm scale (useful for atmospheric particle concentration data). This could be a color palette config field. Maybe something like this?

```js
"raster:palette": {
  "breakpoints": [
    ...
    [-6, 'rgb(44, 167, 197)'],
    [-4, 'rgb(67, 181, 197)'],
    [-2, 'rgb(99, 200, 197)'],
    [0,  'rgb(127, 205, 187)'],
    [2,  'rgb(152, 220, 166)'],
    [4,  'rgb(199, 233, 180)'],
    [6,  'rgb(220, 242, 198)'],
    ...
  ],
  "scale": "linear", // enum values: linear (default), logarithmic
}
```

// cc @DanielJDufour I would appreciate your thoughts about this topic.

**Comment by drwelby** [comment]
This was discussed in several issues in the Classification extension repo (such as https://github.com/stac-extensions/classification/issues/9) and the opinion that kept coming up is that palettes like this represent a styling choice for the viewer and are not really metadata. One alternative discussed was to instead link to a styling file or color map as an asset.

**Comment by zakjan** [comment]
Thanks for the link, I haven't found it before. https://github.com/stac-extensions/classification/issues/3 seems also relevant.

> the opinion that kept coming up is that palettes like this represent a styling choice for the viewer and are not really metadata

This difference makes sense especially because there is no textual description for the palette values, so it doesn't fit classification extension. Also, a single item could have multiple palettes (light/dark), with potentially different values.

> One alternative discussed was to instead link to a styling file or color map as an asset.

If a color palette is in a separate asset, then it needs just a new asset role?

```
"assets": {
  "palette": { "href": "palette.cpt", "type": "text/plain", "roles": ["palette"] }
}
```

Re color palette format, [gdaldem color-relief color_text_file](https://gdal.org/programs/gdaldem.html#color-relief) seems as a good candidate to recommend. It's compatible with [GRASS](https://grass.osgeo.org/grass80/manuals/r.colors.html), [ArcGIS](https://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/creating-a-color-map-clr-file.htm), and also accepts [GMT](https://docs.generic-mapping-tools.org/latest/makecpt.html).

GMT is interesting for a reference about both my advanced ideas:
- non-RGB color models - there is HSV. GDAL checks for a color model comment and fails if it's not RGB ([here](https://github.com/OSGeo/gdal/blob/3f6c8dc3a56825b24e69634c5d2c3abd74a53ce5/apps/gdaldem_lib.cpp#L1872-L1883)). Potentially GDAL could be updated to support non-RGB color models.
- logarithmic scale - palette can be created with `-Tmin/max+l` param, so that it outputs linear color breaks from a logarithmic scale. This is good enough, a color palette just needs to be generated with enough color breaks.

**Comment by zakjan** [comment]
I started working on [cpt2json](https://github.com/zakjan/cpt2json), a library to parse color palette files. It's not released yet, there are a few edge cases with GMT files left.

**Comment by drwelby** [comment]
Thanks @zakjan, I have added info about your work to the README

**Comment by zakjan** [comment]
It's published! I welcome any comments in the repo, especially about the output object.

**Comment by m-mohr** [comment]
Closing as this seems to be not really raster metadata, but could be provided through links to such files as discussed above.
