### ISSUE TITLE
Collection-level raster details

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#26]
We need to provide collection-level raster details for our data cubes.

Could we also allow something like:

````
{
  "id": "TERRASCOPE_S2_NDVI_V2",
  "title": "Sentinel-2 NDVI last 2 years over Europe + selected areas, by Terrascope.",
  "summaries": {
    "raster:bands": [
      {
        "name": "NDVI_10M",
        "nodata": 255,
        "data_type": "uint8",
        "statistics": {"minimum": 0, "maximum: "254"}
      },
      {
        "name": "SCENECLASSIFICATION_20M",
        ...
      }
    ],
    "instruments": [
      "MSI"
    ],
    "platform": [
      "SENTINEL-2"
    ]
  },
  ...
}
````

**Comment by jdries** [comment]
I just finally discovered what item_assets is for. I'm actually wondering if that is perhaps a better option for this rather than trying to use summaries?
We indeed have collections without items, so that is maybe weird, but other than that, this seems to be the standardized approach to documenting metadata about things that are tied to assets, like bands?
If using the summaries options, would anyone outside of an openEO context really understand our metadata?

**Comment by m-mohr** [comment]
@jdries Right now summarizing eo:bands in summaries is fine, I think. The main issue is that raster:bands is just defined on the asset level, but then we also go forward with https://github.com/radiantearth/stac-spec/discussions/1213 and there the question also occurs: What should it apply to? What's actually the meaning of bands outside of assets?

The issue with item assets is that there is no asset for (collection-less) data cubes and defining one with an arbitrary key seems less understandable than having them in summaries.

**Comment by matthewhanson** [comment]
Discussed at STAC sprint.

Will be resolved in https://github.com/radiantearth/stac-spec/pull/1254
