### ISSUE TITLE
raster:bands list with more than one item

### ISSUE THREAD

**Issue by joemcglinchy** [stac-extensions/raster#44]
Hello, was wondering if this fits the `raster` asset role spec or not. Say we have a Top-of-Atmosphere STAC item and we wish to provide two levels of scale/offset if the user wants to convert the DNs to TOA radiance, or TOA reflectance. Is this supported by the spec?

potential example:

```
"assets": {

    "BAND1": {
        "title": "TOA BAND1",
        "raster:bands": 
        [
            {
                "scale": 0.1,
                "offset": 1.0,
                "nodata": 0,
                "unit": "W⋅sr−1⋅m−2"
            },
            {
                "scale": 0.5,
                "offset": 5.0,
                "nodata": 0,
                "unit": "reflectance"
            }
        ]
}
```

**Comment by matthewhanson** [comment]
Hi @joemcglinchy, this would not be supported by this extension, as the expectation would be that there were 2 bands of data in the data file.

However, you could do this by having two different assets, each with different scale and offset. A potential problem however is that you *should* have scale/offset embedded within the data files themselves, so one of the assets would be in conflict with what is in the file. This isn't a major problem since clients (GDAL, ODC) will not automatically apply the scale/offset so as long as it's documented and client side processing uses the correct scale/offset it would be fine.

**Comment by joemcglinchy** [comment]
bumping. in addition to those questions, if a client automatically applies scale and offset, do they need to be named specifically `scale` and `offset` in this extension?

**Comment by m-mohr** [comment]
Yes, the names for the fields going forward will be raster:scale and raster:offset. All other questions seem implementation specific to me.
